// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqBNTODepExBi9nfuRf1iqwtOUZZy1mm8',
    appId: '1:133136651371:web:1aa96763bfe2be461b4d2e',
    messagingSenderId: '133136651371',
    projectId: 'trezo-a5c06',
    authDomain: 'trezo-a5c06.firebaseapp.com',
    storageBucket: 'trezo-a5c06.appspot.com',
    measurementId: 'G-JS9EWH2S3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8D6qjIfRwLdXotUF--VCYzUCyoax8D28',
    appId: '1:133136651371:android:282aba39719a8ef61b4d2e',
    messagingSenderId: '133136651371',
    projectId: 'trezo-a5c06',
    storageBucket: 'trezo-a5c06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzVsgQfRsCfbMxsocCEmzA8AwAnCAPDH4',
    appId: '1:133136651371:ios:61e8e9783dea80471b4d2e',
    
    messagingSenderId: '133136651371',
    projectId: 'trezo-a5c06',
    storageBucket: 'trezo-a5c06.appspot.com',
    iosBundleId: 'com.example.collectionerCatalogue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzVsgQfRsCfbMxsocCEmzA8AwAnCAPDH4',
    appId: '1:133136651371:ios:61e8e9783dea80471b4d2e',
    messagingSenderId: '133136651371',
    projectId: 'trezo-a5c06',
    storageBucket: 'trezo-a5c06.appspot.com',
    iosBundleId: 'com.example.collectionerCatalogue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqBNTODepExBi9nfuRf1iqwtOUZZy1mm8',
    appId: '1:133136651371:web:2c9aa298b42f2c991b4d2e',
    messagingSenderId: '133136651371',
    projectId: 'trezo-a5c06',
    authDomain: 'trezo-a5c06.firebaseapp.com',
    storageBucket: 'trezo-a5c06.appspot.com',
    measurementId: 'G-GHZKFCFSWX',
  );

}
